version: '3.8'

services:
  # 1. MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: hyperqueue_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=hyperqueue_task_db
    volumes:
      - mongo_data:/data/db
    networks:
      - hyperqueue_net

  # 2. Redis Server (BullMQ Queue & Session Cache)
  redis:
    image: redis:alpine
    container_name: hyperqueue_redis
    ports:
      - "6379:6379"
    networks:
      - hyperqueue_net

  # 3. Node.js Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: hyperqueue_backend_api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/hyperqueue_task_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_SECRET=hyperqueue_super_secret_access_key_2026
      - JWT_REFRESH_SECRET=hyperqueue_super_secret_refresh_key_2026
    depends_on:
      - mongodb
      - redis
    networks:
      - hyperqueue_net

  # 4. Next.js Frontend Web Application
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: hyperqueue_frontend_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - hyperqueue_net

volumes:
  mongo_data:

networks:
  hyperqueue_net:
    driver: bridge
